on: 
  push:
    branches:
      - 'main'
jobs:
  publish-nuget-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
      - run: dotnet pack Dungen/Dungen.csproj --configuration Release
      - run: dotnet nuget push "Dungen/bin/Release/dungen.*.nupkg" --skip-duplicate --api-key ${{ secrets.NUGET_ORG_API_KEY }} --source https://api.nuget.org/v3/index.json

